analytics:

  target: taxi_dev
  outputs:
    tbc_dev:
      type: clickhouse
      schema: taxi_dev
      password: ''
    
    tbc_test:
      type: clickhouse
      schema: taxi_test
      password: ''

    tbc_production:
      type: clickhouse
      schema: taxi_production
      password: ''

    
    
