taxi_data_analytics:

  target: taxi_dev
  outputs:
    tbc_dev:
      type: clickhouse
      schema: taxi_dev
      password: ''
    
    taxi_test:
      type: clickhouse
      schema: taxi_test
      password: ''

    taxi_production:
      type: clickhouse
      schema: taxi_production
      password: ''

    
    
